<?php

namespace Infinity\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class InfinitySettingsController extends InfinityBaseController
{
    public function index(Request $request): View|Factory|Application
    {
        $this->setOrder('key', 'ASC');

        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
